name: Tutor Integration Tests
on: [pull_request]

jobs:
  integration-test:
    name: Tutor Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tutor_version: ['<18.0.0', '<19.0.0']
    steps:
      - name: Run Integration Tests
        uses: eduNEXT/integration-test-in-tutor@mjh/run-integration-tests-outside-container
        with:
          tutor_version: ${{ matrix.tutor_version }}
          app_name: 'eox-core'
          openedx_extra_pip_requeriments: 'eox-tenant'
          shell_file_to_run: 'scripts/execute_integration_tests.sh'
          fixtures_file: 'fixtures/initial_data.json'
